name: build-windows

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-windows:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-2022, windows-2019, windows-2016]
                swift: [5.4.2]
        steps:
            -   uses: actions/checkout@v2
            
            -   name: build 
                uses: MaxDesiatov/swift-windows-action@v1
                with:
                    swift-version: "${{ matrix.swift }}"
                    shell-action: |
                        swift --version
                        swift build
